### ISSUE TITLE
FAKE DEV

### ISSUE THREAD

**Issue by ghost** [BajanVlogs/ModBanSystem#5]
You know they won't accept it. You know why?
First, task isn't good
Second, youre fucking asshole! DONT UPLOAD MY PLUGIN -.-

**Comment by Thunder33345** [comment]
hi there, poggit reviewer here
if you can proof your claims we can do something about that
and yes task is bad
very bad because this runs every second
also see this which is total glore
https://github.com/BajanVlogs/ModBanSystem/blob/master/src/ModBanSystem/Main.php#L154-L175

**Comment by pranavbhuv** [comment]
xZd

**Comment by pranavbhuv** [comment]
Pls do t take this down it’s time scammer freaking dev has his own medicine

**Comment by ghost** [comment]
@Thunder33345  You can contact Awzaw, he already review it when i uploaded it. Please stop this fakedev from claiming other plugins.

**Comment by ghost** [comment]
@QuiverlyRivalry  Eat your words
![haters](https://user-images.githubusercontent.com/13855537/34451139-f764da22-ed57-11e7-9d72-0d3f02c50a22.png)
