### ISSUE TITLE
Haha

### ISSUE THREAD

**Issue by TwistedAsylumMC** [BajanVlogs/ModBanSystem#6]
Great dev love free shit

**Comment by YHC2538** [comment]
Nah, I like free plugins. I'll thank this guy instead :p

**Comment by YHC2538** [comment]
I f##king hate plugin devs that make their plugin "paid". I don't f##king get why they do that and are afraid THEIR plugins getting stolen if they wanted to put it for public sale. Its very annoying when they just like to show off they can code and others can't. 

Thanks to this guy that made it free to public XD

**Comment by OfficialLilKev** [comment]
Np anytime
